### ISSUE TITLE
[Fabric 1.19.4] Crash on game load

### ISSUE THREAD

**Issue by Maloonkey** [Builderb0y/BigGlobe#1]
Using latest Fabric Loader, no other mods besides the latest Fabric API

```
Time: 2023-04-09 13:15:29
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bigglobe'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NoClassDefFoundError: builderb0y/autocodec/AutoCodec
	at builderb0y.bigglobe.compat.ClothConfigCompat.init(ClothConfigCompat.java:21)
	at builderb0y.bigglobe.config.BigGlobeConfig.<clinit>(BigGlobeConfig.java:24)
	at builderb0y.bigglobe.BigGlobeMod.onInitialize(BigGlobeMod.java:62)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
Caused by: java.lang.ClassNotFoundException: builderb0y.autocodec.AutoCodec
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more
```

[crash-2023-04-09_13.15.29-client.txt](https://github.com/Builderb0y/BigGlobe/files/11186061/crash-2023-04-09_13.15.29-client.txt)

**Comment by Builderb0y** [comment]
Should be fixed in version 3.2.1. For whatever reason, gradle wasn't including AutoCodec in the mod jar file.
