### ISSUE TITLE
Error saying Fabric isn't installed, even though it is.

### ISSUE THREAD

**Issue by thomasflrs** [Builderb0y/BigGlobe#27]
Every time I try to start the game in MultiMC I get this error even though Fabric is already installed:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'Big Globe' (bigglobe) 4.4.0 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Builderb0y** [comment]
Do you also have [fabric API](https://modrinth.com/mod/fabric-api)? Fabric and Fabric API are both required for Big Globe. Though it doesn't help that Fabric API's internal name is just "fabric", and this is what the error message shows, which can cause some confusion.

**Comment by Builderb0y** [comment]
So... was that the issue? Was it just a simple case of Fabric Loader being present, but Fabric API missing?

**Comment by Builderb0y** [comment]
I'm gonna assume that silence means you got it working.
