### ISSUE TITLE
(4.0.2 1.20.6) mojang loading screen loop when hyperspace is disabled

### ISSUE THREAD

**Issue by maximumpower55** [Builderb0y/BigGlobe#7]
```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Failed to create model for minecraft:pig
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) [transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) [transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [transformed-mod-minecraft-v1.20.6.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) [quilt-loader-0.26.0-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) [quilt-loader-0.26.0-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.26.0-beta.1.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.IllegalArgumentException: Failed to create model for minecraft:pig
	at net.minecraft.class_5619.method_32174(class_5619.java:170) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:209) ~[fastutil-8.5.12.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1000) ~[fastutil-8.5.12.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:211) ~[fastutil-8.5.12.jar:?]
	at net.minecraft.class_5619.method_32176(class_5619.java:166) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_898.method_14491(class_898.java:407) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 17 more
Caused by: java.lang.NullPointerException: null key in entry: null=builderb0y.bigglobe.entities.WaypointEntityRenderer@6ac18035
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:31) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:54) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:341) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:450) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.class_5619.method_32174(class_5619.java:168) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:209) ~[fastutil-8.5.12.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1000) ~[fastutil-8.5.12.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:211) ~[fastutil-8.5.12.jar:?]
	at net.minecraft.class_5619.method_32176(class_5619.java:166) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_898.method_14491(class_898.java:407) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 17 more
```

**Comment by Builderb0y** [comment]
I knew I should've tested that... fixed in version 4.1.0. I was so close to releasing that version when I noticed this issue too. Glad I did notice it first!
