### ISSUE TITLE
Generating Medium and Large dungeons causes game to crash

### ISSUE THREAD

**Issue by TheCodedProf** [Builderb0y/BigGlobe#75]
Was flying through the world with elytra when game suddenly crashed, according to the logs which I have provided below it's trying to generate a Medium Dungeon (I've had it happen for large ones too).

Running latest bigglobe version and no other mods that would effect the terrain.

Logs:
```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2024-12-07 17:37:32
Description: Exception generating new chunk

java.lang.IllegalStateException: Key bigglobe:overworld/dungeons/medium not present in registry minecraft:worldgen/configured_feature. Note: a tag with this name exists. Did you forget to prefix the name with '#'?
	at builderb0y.bigglobe.dynamicRegistries.BetterRegistry.requireEntry(BetterRegistry.java:44)
	at builderb0y.bigglobe.dynamicRegistries.BetterRegistry.getById(BetterRegistry.java:64)
	at builderb0y.bigglobe.util.DelayedEntryList.lambda$resolve$1(DelayedEntryList.java:170)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at builderb0y.bigglobe.util.DelayedEntryList.resolve(DelayedEntryList.java:173)
	at builderb0y.bigglobe.util.DelayedEntryList.entryList(DelayedEntryList.java:82)
	at builderb0y.bigglobe.util.DelayedEntryList.randomObject(DelayedEntryList.java:148)
	at builderb0y.bigglobe.structures.dungeons.AbstractDungeonStructure$RoomDungeonPiece.method_14931(AbstractDungeonStructure.java:346)
	at builderb0y.bigglobe.structures.dungeons.MediumDungeonStructure$Room.method_14931(MediumDungeonStructure.java:150)
	at builderb0y.bigglobe.chunkgen.BigGlobeScriptedChunkGenerator.generateStructures(BigGlobeScriptedChunkGenerator.java:792)
	at builderb0y.bigglobe.chunkgen.BigGlobeScriptedChunkGenerator.method_12102(BigGlobeScriptedChunkGenerator.java:708)
	at net.minecraft.class_9310.method_57610(class_9310.java:103)
	at net.minecraft.class_9770.method_60560(class_9770.java:33)
	at net.minecraft.class_3898.method_60442(class_3898.java:632)
	at net.minecraft.class_9761.method_60461(class_9761.java:96)
	at net.minecraft.class_9759.method_60428(class_9759.java:143)
	at net.minecraft.class_9759.method_60427(class_9759.java:121)
	at net.minecraft.class_9759.method_60432(class_9759.java:74)
	at net.minecraft.class_9759.method_60424(class_9759.java:59)
	at net.minecraft.class_3898.method_60446(class_3898.java:665)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Worker-Main-26
Stacktrace:
	at builderb0y.bigglobe.dynamicRegistries.BetterRegistry.requireEntry(BetterRegistry.java:44)
	at builderb0y.bigglobe.dynamicRegistries.BetterRegistry.getById(BetterRegistry.java:64)
	at builderb0y.bigglobe.util.DelayedEntryList.lambda$resolve$1(DelayedEntryList.java:170)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at builderb0y.bigglobe.util.DelayedEntryList.resolve(DelayedEntryList.java:173)
	at builderb0y.bigglobe.util.DelayedEntryList.entryList(DelayedEntryList.java:82)
	at builderb0y.bigglobe.util.DelayedEntryList.randomObject(DelayedEntryList.java:148)
	at builderb0y.bigglobe.structures.dungeons.AbstractDungeonStructure$RoomDungeonPiece.method_14931(AbstractDungeonStructure.java:346)
	at builderb0y.bigglobe.structures.dungeons.MediumDungeonStructure$Room.method_14931(MediumDungeonStructure.java:150)
	at builderb0y.bigglobe.chunkgen.BigGlobeScriptedChunkGenerator.generateStructures(BigGlobeScriptedChunkGenerator.java:792)
	at builderb0y.bigglobe.chunkgen.BigGlobeScriptedChunkGenerator.method_12102(BigGlobeScriptedChunkGenerator.java:708)
	at net.minecraft.class_9310.method_57610(class_9310.java:103)
	at net.minecraft.class_9770.method_60560(class_9770.java:33)

-- Chunk to be generated --
Details:
	Status being generated: minecraft:features
	Location: -175,160
	Position hash: 691489734481
	Generator: builderb0y.bigglobe.chunkgen.BigGlobeScriptedChunkGenerator@3016ab6b
Stacktrace:
	at net.minecraft.class_3898.method_60442(class_3898.java:632)
	at net.minecraft.class_9761.method_60461(class_9761.java:96)
	at net.minecraft.class_9759.method_60428(class_9759.java:143)
	at net.minecraft.class_9759.method_60427(class_9759.java:121)
	at net.minecraft.class_9759.method_60432(class_9759.java:74)
	at net.minecraft.class_9759.method_60424(class_9759.java:59)
	at net.minecraft.class_3898.method_60446(class_3898.java:665)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by Builderb0y** [comment]
Hopefully fixed in V4.8.3. At the very least, these errors should be caught better now, and no longer crash the game.
