### ISSUE TITLE
settings menu dont work

### ISSUE THREAD

**Issue by MottiDowerro** [Builderb0y/BigGlobe#78]
![image](https://github.com/user-attachments/assets/5de9359c-8c34-4b71-b68f-2455eddb0f23)
[15:08:44] [Render thread/INFO]: ColumnEntryRegistry end load: builderb0y.bigglobe.columns.scripted.ColumnEntryRegistry$Loading@41623b72; override: null
java.lang.Throwable: The following stack trace is NOT an error. It is debug information that is useful if you get data pack validation issues and none of your worlds load correctly.
	at knot/builderb0y.bigglobe.columns.scripted.ColumnEntryRegistry$Loading.endLoad(ColumnEntryRegistry.java:226) ~[Big%20Globe-4.8.3-MC1.21.1.jar:?]
	at knot/net.minecraft.class_7237.md93071b$bigglobe$lambda$bigglobe_finishLoadingColumnEntryRegistry$0$0(class_7237.java:539) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:145) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7196.method_45694(class_7196.java:182) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7196.method_54610(class_7196.java:137) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7196.method_57780(class_7196.java:323) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7196.method_57781(class_7196.java:313) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7196.method_57782(class_7196.java:278) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7196.method_57784(class_7196.java:243) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_528$class_4272.method_20164(class_528.java:434) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_528$class_4272.method_25402(class_528.java:411) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_350.method_25402(class_350.java:315) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at knot/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.3.jar:?]
	at knot/org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at knot/org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) [lwjgl-glfw-3.3.3.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1310) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]

**Comment by Builderb0y** [comment]
That is the wrong stack trace for the error in your chat menu. And it's also unrelated to the title of this issue. I have seen similar chat messages before, but they're rare, and probably a race condition.

**Comment by MottiDowerro** [comment]
> That is the wrong stack trace for the error in your chat menu. And it's also unrelated to the title of this issue. I have seen similar chat messages before, but they're rare, and probably a race condition.

Let's say, what then to do with the settings menu?

**Comment by Builderb0y** [comment]
The error in the chat menu has been fixed in V4.8.4. Still not sure what issue you're having with the settings menu though.

**Comment by MottiDowerro** [comment]
> The error in the chat menu has been fixed in V4.8.4. Still not sure what issue you're having with the settings menu though.

fixed by installing cloth config mod but this is not in the dependencies

**Comment by Builderb0y** [comment]
Ah, yeah. I didn't list it as a dependency because it's optional. The rest of big globe (minus the settings menu) should work just fine without cloth config installed. Glad you got it fixed though!
